#ifndef BLUETOOTHCOM_GLOBAL_H
#define BLUETOOTHCOM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLUETOOTHCOM_LIBRARY)
#  define BLUETOOTHCOMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLUETOOTHCOMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLUETOOTHCOM_GLOBAL_H
